#database configuration
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movies?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: "ronysmile34@gmail.com"
    password: "bqex fqwq zppv wpwy"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


project:
  poster: posters/

base:
  url: "http://localhost:8080"